### ISSUE TITLE
address.wast hits error

### ISSUE THREAD

**Issue by jaroslov** [FastVM/Web49#5]
I'm on macOS Ventura; I did the following:

1. Cloned the source
2. Built ("make all")
3. Tried to run "./bin/wat2wasm test/core/address.wast"

The output I get is this:

> $$$ ./bin/wat2wasm test/core/address.wast
> unexpected word: `` byte=256

**Comment by ShawSumma** [comment]
This is a known error that baffels me, it appears that comments in the file are making the expression parser do something very odd... Not sure what. Will investigate further.

**Comment by ShawSumma** [comment]
Another thing is taht wat2wasm cannot handle wast files. This is intentional as what would it output? 
wat = WAsm Text
wast = WAsm Spec Test

**Comment by jaroslov** [comment]
Ah. Ok. Comments aren't necessary — I was just trying to test drive this guy.
